site_name: WLANPi Documentation Project
nav:
    - Home: index.md
    - About: about.md
    - Getting Started:
        - Overview: getting_started_overview.md
        - Buy a Kit: getting_started_buy_kit.md
        - Build Your Own: getting_started_build_your_own.md
    - Packages: packages.md
    - Suppliers: suppliers.md
    - News: news.md
    - Support: support.md
    - Getting Involved: get_involved.md
    - Useful Links: useful_links.md
theme:
    name: 'material'
    logo:
        icon: wifi
plugins:
    - search
    - git-revision-date

