site_name: WLANPi Documentation Project
nav:
    - Home: index.md
    - About: about.md
    - Getting Started: getting_started.md
    - Packages: packages.md
    - Suppliers: suppliers.md
    - News: news.md
    - Support: support.md
    - Getting Involved: get_involved.md
    - Useful Links: useful_links.md
theme:
    name: 'material'
    logo:
        icon: wifi
